include-file = ~/.config/polybar/colors.ini

;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[bar/toph]
monitor = ${env:MONITOR:eDP-1}
width = 100%
height = 28pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

bottom = false

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = " "
separator-foreground = ${colors.surface2}

font-0 = "JetBrainsMono Nerd Font:size=11;3"
font-1 = "JetBrainsMono Nerd Font:size=14;4"

modules-left = xworkspaces
modules-center = spotify
modules-right = pulseaudio battery wlan date
; no memory needed
cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = i3
; override-redirect = true


[bar/toph-hdmi]
inherit = bar/toph
monitor = ${env:MONITOR:HDMI-1-0}

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.surface1}
label-active-foreground = ${colors.blue}
label-active-underline= ${colors.blue}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2
label-occupied-foreground = ${colors.text}

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.surface2}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/spotify]
type = custom/script
interval = 1
format-prefix = "  "
format = <label>
exec = /usr/bin/python3 $HOME/.config/polybar/spotify.py
format-foreground = ${colors.primary}

[module/gpu]
type = custom/script
exec = nvidia-smi --query-gpu=utilization.gpu,temperature.gpu,memory.used,memory.total --format=csv,noheader,nounits | awk -F',' '{printf "%2d%% %d°C %dMB/%dMB", $1, $2, $3, $4}'
interval = 2
format-prefix = "GPU "
format-prefix-foreground = ${colors.primary}

[module/battery-test]
type = internal/battery
battery = BAT1
adapter = ACAD
format-charging = CHARGING
format-discharging = DISCHARGING

[module/battery]
type = internal/battery
battery = BAT1        
adapter = ACAD       
full-at = 99
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = "Full"

low-at = 10
label-low-foreground = ${colors.alert}
; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = Charging %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = Discharging %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = Fully charged

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = BATTERY LOW

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %local_ip%

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S
date-alt = %H:%M

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/bluetooth]
type = custom/script
exec = bluetoothctl show | grep -q "Powered: yes" && bluetoothctl info | grep -oP '(?<=Name: ).*' || echo "BT off"
interval = 5
; vim:ft=dosini
