# Deliberately plain, like i3lock with no arguments.
background {
    monitor =
    path = ~/Pictures/wallpapers/nope/ign_lonely-man.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = rgba(4c7899ff)
    inner_color = rgba(000000cc)
    font_color = rgba(ffffffff)
    placeholder_text = <i>Password</i>
    fade_on_empty = false
    position = 0, -50
    halign = center
    valign = center
}
