# i3 equivalent: exec_always feh --bg-fill ~/Pictures/wallpapers/nope/ign_lonely-man.png
preload = ~/Pictures/wallpapers/nope/ign_lonely-man.png
wallpaper = , ~/Pictures/wallpapers/nope/ign_lonely-man.png
splash = false
ipc = on
