# vim:ft=kitty
## name: Extra Dark

# Basic colors
foreground           #cdd6f4
background           #050507
selection_foreground #cdd6f4
selection_background #242438

# Cursor colors
cursor            #f5e0dc
cursor_text_color #050507

# URL underline color when hovering with mouse
url_color #89dceb

# Window border colors and terminal bell colors
active_border_color   #89b4fa
inactive_border_color #181825
bell_border_color     #f9e2af
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #050507
active_tab_background   #89b4fa
inactive_tab_foreground #a6adc8
inactive_tab_background #11111b
tab_bar_background      #050507
tab_bar_margin_color    none

# Mark colors
mark1_foreground #050507
mark1_background #89b4fa
mark2_foreground #050507
mark2_background #f38ba8
mark3_foreground #050507
mark3_background #f9e2af

# The basic 16 colors
color0  #08080d
color8  #313244

color1  #f38ba8
color9  #eba0ac

color2  #a6e3a1
color10 #a6e3a1

color3  #f9e2af
color11 #f9e2af

color4  #89b4fa
color12 #89b4fa

color5  #cba6f7
color13 #f5c2e7

color6  #89dceb
color14 #94e2d5

color7  #bac2de
color15 #cdd6f4
